### ISSUE TITLE
Polls create but all options return 400

### ISSUE THREAD

**Issue by NewEvolution** [M-Mueller/mattermost-poll#21]
Just set up the integration and it's half-working.

I can create polls which show up as expected, but no users are able to add responses, and the "End Poll" button is unresponsive as well.

Requests on button press are made to `/api/v4/posts/some26characterstring/actions/someother26characterstring`

Button clicks return an HTTP 400 and a response like
```JSON
{
  "id":"api.post.do_action.action_integration.app_error",
  "message":"Action integration error",
  "detailed_error":"",
  "request_id":"hsn5igzp6frndkyrchjzf4ssra",
  "status_code":400
}
```

Turning on file logging in `settings.py` shows no output whatsoever on button press so I'd imagine the posts are not hitting the app.

Any ideas on where to start looking for further debugging would be appreciated.

**Comment by M-Mueller** [comment]
Are you using docker? Maybe this is an issue with the last pull request.

**Comment by NewEvolution** [comment]
No, running it directly.

**Comment by M-Mueller** [comment]
Can you try to run the server with:
```
FLASK_APP=app.py FLASK_DEBUG=1 flask run --host <ip> --port <port>
```
This should show a lot more logging on the console (for some reason newer flask version don't manage to log to the file any more).

You can also try to send the request directly with curl:
```
curl --data "user_id=1234&text=test" <host>:<port>
curl -X POST -H "Content-Type:application/json" --data '{"user_id":"1234", "context":{"poll_id":<number_from_previous_reponse>,"vote":0}}' <host>:<port>/vote
```

**Comment by NewEvolution** [comment]
Thanks for the info, part of the problem was that I'm running Mattermost and all its plugins behind 
an NGINX reverse proxy and hadn't configured endpoints for `/vote` and `/end`. With those set up I now have some more useful output.

Clicking on any of the vote (or End Poll) buttons now reaches the flask app, but results in the following requests & their HTTP response codes, in this order:
```
POST /vote - 301
POST /api/v4/posts/5apbgjbof3g3ufqwhn91waekor/actions/x5zha4up3bym78f48g16doqz1w - 400
GET /vote - 405
```

The first `POST /vote` request produces no output from the flask app.

My NGINX config is set to return a 301 for non-HTTPS requests, so that may be involved, though I've set the `MATTERMOST_URL` in `settings.py` to the full HTTPS URL.

The second post to the `/api` route does not produce output from the flask app, but returns this with its 400:
```json
{
  "id":"api.post.do_action.action_integration.app_error",
  "message":"Action integration error",
  "detailed_error":"",
  "request_id":"ego1megtw3fetjchg8bhyceuoo",
  "status_code":400
}
```

The `GET /vote` produces this output from the flask app:
```
DEBUG:flask.app:Response status: 405 METHOD NOT ALLOWED
DEBUG:flask.app:Response data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
WARNING:tornado.access:405 GET /vote (127.0.0.1) 0.95ms
```

**Comment by M-Mueller** [comment]
I finally found some time to play around with the SSL stuff, unfortunately I couldn't get it to work with self-signed certificates. In theory it should be enough to add your certificate and key to the HTTPServer in run.py:
```
http_server = httpserver.HTTPServer(
    wsgi.WSGIContainer(app.app),
    ssl_options={
        "certfile": "<path to certificate file>",
        "keyfile": "<path to key file>",
    }
)
```
Since you are already using nginx, you can also ignore the run.py and use nginx directly as WSGI server: https://vladikk.com/2013/09/12/serving-flask-with-nginx-on-ubuntu/
In this case nginx should take care about HTTPS.

That the `GET /vote` returns a 405 is expected, since the server only handles POST requests.

**Comment by weekscharlie** [comment]
I am having the same issue with the Matterpoll feature (Mattermost server behind NGINX proxy).  However, I'm not convinced the problem is linked to NGINX.  On our internal network, Mattermost resolves directly to the app server (bypasses NGINX) and we have the same issue with the buttons not working.  Our NGINX server is using a publicly signed certificate and our app server is using a trusted internally signed (AD CA) certificate.

Log messages when clicking a matterpoll button externally:
2018-09-18T09:53:47.138-0400    info    http/server.go:1743     http: TLS handshake error from 10.2.27.45:53772: remote error: tls: bad certificate     {"source": "httpserver"}
2018-09-18T09:53:47.138-0400    error   web/context.go:60       Action integration error        {"path": "/api/v4/posts/dtgp4ktysbbs3dqqaway9ip4fc/actions/e4dfdahoft89zpf5ymwipkx4eh", "request_id": "uj6m79t34jnqxfzmobkxn1udpw", "ip_addr": "10.2.201.254", "user_id": "ohurihfa17dsmm3op8g3jiz95o", "method": "POST", "err_where": "DoPostAction", "http_code": 400, "err_details": "err=Post https://chat.globalendowment.com/plugins/com.github.matterpoll.matterpoll/api/v1/polls/y6ykz8hj93fb5rdaewsfanxoxc/vote/0: x509: certificate signed by unknown authority"}

Log message when clicking a matterpoll button internally:
2018-09-18T09:55:02.248-0400    info    http/server.go:1743     http: TLS handshake error from 10.2.27.45:53778: remote error: tls: bad certificate     {"source": "httpserver"}
2018-09-18T09:55:02.248-0400    error   web/context.go:60       Action integration error        {"path": "/api/v4/posts/ksao3e38u3f7dptoieouyikptr/actions/o1cscfguti8b3qsw3pjykion1c", "request_id": "b5z1ka7bqjdk3c9isegt4exqxw", "ip_addr": "10.1.41.102", "user_id": "ohurihfa17dsmm3op8g3jiz95o", "method": "POST", "err_where": "DoPostAction", "http_code": 400, "err_details": "err=Post https://chat.globalendowment.com/plugins/com.github.matterpoll.matterpoll/api/v1/polls/38kubh9iyjdr783yqnqymqdu4y/vote/0: x509: certificate signed by unknown authority"}

Anyone have any ideas?

**Comment by M-Mueller** [comment]
Does the poll server use https as well?

**Comment by archanbhatt** [comment]
I have a similar problem as @weekscharlie. Let me know if you have any solution.

**Comment by weekscharlie** [comment]
Sorry for the delay, @M-Mueller.  The poll server also uses https, as we'd rather now allow unencrypted Mattermost traffic internally.  To be clear, the poll server is also our Mattermost app server.

**Comment by M-Mueller** [comment]
I think this might be the same issue as here: https://gitlab.com/gitlab-org/gitlab-workhorse/issues/177

I got the same error (x509: certificate signed by unknown authority) when I tried it with a self-signed certificate (however, for me all /poll command failed with that error). Once I set SSL_CERT_DIR to a directory containing my certificate it worked.

**Comment by NewEvolution** [comment]
Well, after poking around I've found the root cause of the issue.  Turns out that the posts to `/vote` and `/end` are being made over http whereas the initial post to `/poll` uses https as expected.

Failing NGINX site config:
```nginx
upstream polls {
  server 127.0.0.1:5000;
}

server {
  listen 80;
  listen [::]:80;
  server_name chat.company.io;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name chat.company.io;

  location /poll {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://polls/;
  }

  location ~ /(vote|end) {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://polls/$1;
  }
}
```


Working NGINX site config:
```nginx
upstream polls {
  server 127.0.0.1:5000;
}

server {
  listen 80;
  listen [::]:80;
  server_name chat.company.io;

  location ~ /(vote|end) {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://polls/$1;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name chat.company.io;

  location /poll {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://polls/;
  }
}
```

~~Working on a PR so the buttons created by the `/poll` post response respect the protocol specified in `settings.py`.~~

Actually, looks like it's an issue with [Flask not respecting the `X-Forwarded-Proto` header](https://stackoverflow.com/questions/23347387/x-forwarded-proto-and-flask).  Going to attempt the fix specified.

**Comment by NewEvolution** [comment]
Plugging
```python
from werkzeug.contrib.fixers import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app)
```
into `app.py` did indeed solve the issue of the vote/end button URLs being generated with the incorrect protocol.

I've just hacked it in for the moment, as it's not a setting you'd want for instances of this plugin that are _not_ behind a proxy.  Perhaps it could be configured via a flag in the `settings.py` in future releases?

**Comment by M-Mueller** [comment]
Thank you very much for investigating this! I added a setting that applies the ProxyFix.

**Comment by archanbhatt** [comment]
thank you so much @M-Mueller and @NewEvolution. Really appreciated. I will test it in early January and will let you know if I have any further issue.
