### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by silberzwiebel** [M-Mueller/mattermost-poll#27]
I'd like to have this nice poll plugin in languages different than English (in particular: in German). Happy to translate it to German but not sure if and how this works. It would be great if the poll can "just" use the same mattermost's language setting. Thanks!

**Comment by M-Mueller** [comment]
I wanted to learn how internationalization works in Python anyway, so I'm happy to do that.

Figuring out the correct language for each user could be tricky though, since it is not part of the request send by Mattermost. Maybe there is something in the API.

**Comment by M-Mueller** [comment]
The poll is now using the account's language setting. The language will be the same for everyone seeing the poll. E.g. if you create a poll in German, English users will see it in German as well. This is a restriction of the Mattermost slash command but I think it makes sense anyway since the message the user enters is not translated in the first place.
The user can also force a certain language with the `--locale` command.

**Comment by silberzwiebel** [comment]
Thanks, that was quick :)
