### ISSUE TITLE
Dockerfile - configuration by environment variables.

### ISSUE THREAD

**Issue by PigNatovsky** [M-Mueller/mattermost-poll#43]
Hello @M-Mueller, thank You for maintaining this project!
My issue is a kind of feature request - in present setup, Dockerfile contains ARG sections for setting configuration of mattermost-poll. It's not the best way of doing that, because builded image isn't universal. Maybe better idea will be making environmental variables placeholders in app.py, so after building an image, we could provide configuration dynamically.
Please, share Your opinion about this idea.

**Comment by M-Mueller** [comment]
I initially used ARG because I read that using ENV for secrets is considered [unsafe](https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/). However, after reading this article again, I don't believe that this is an issue here. If you can read the environment of the process or the log file than you can most likely read the settings.py as well.
So I think this is good idea and I will take a look at it. Might also finally solve #22.

**Comment by PigNatovsky** [comment]
Great! 
Sorry for latency in response -
